server:
  port: 8088



spring:
  datasource:
    #连接MySQL
    url: jdbc:mysql://localhost:3306/socks?useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  
  
mybatis:
  configuration:
   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
   map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.hehe.entity
  
pagehelper:
  helperDialect: mysql
  #合理化设置
  reasonable: true   
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
   #打印SQL信息
   com.hehe.mapper: debug